### ISSUE TITLE
Standard go recipe for libraries

### ISSUE THREAD

**Issue by cyborg-x1** [mem/oe-meta-go#28]
Hi,
I am currently creating a layer based on yours for [influxdb](https://github.com/C-X1/meta-influx). I am stuck at building one simple and two more complex ones.

I did most of the recipes like the ones you did in your layer:

Example(works fine):
```
DESCRIPTION = "github.com/peterh/liner"

GO_IMPORT = "github.com/peterh/liner"

inherit go

SRC_URI = "git://github.com/peterh/liner;protocol=https;destsuffix=${PN}-${PV}/src/${GO_IMPORT}"
SRCREV = "88609521dc4b6c858fd4c98b628147da928ce4ac"
LICENSE = "MIT"
LIC_FILES_CHKSUM = "file://src/${GO_IMPORT}/COPYING;md5=7316a33df6826d7cc2854e686cb9279f"

FILES_${PN} += "${GOBIN_FINAL}/*"
```

Then I had a problem with this package doing this one (does not work):
```
DESCRIPTION = "github.com/rakyll/statik"

GO_IMPORT = "github.com/rakyll/statik"

inherit go

SRC_URI = "git://github.com/rakyll/statik;protocol=https;destsuffix=${PN}-${PV}/src/${GO_IMPORT}"
SRCREV = "e383bbf6b2ec1a2fb8492dfd152d945fb88919b6"
LICENSE = "Apache-2.0"
LIC_FILES_CHKSUM = "file://src/${GO_IMPORT}/LICENSE;md5=a873c5645c184d51e0f9b34e1d7cf559"

inherit go

FILES_${PN} += "${GOBIN_FINAL}/*"
```

I also found your example in the devtools and did:
```
DESCRIPTION = "github.com/rakyll/statik"

inherit go

SRC_URI = "git://github.com/rakyll/statik;protocol=https"
SRCREV = "e383bbf6b2ec1a2fb8492dfd152d945fb88919b6"
LICENSE = "Apache-2.0"
LIC_FILES_CHKSUM = "file://LICENSE;md5=a873c5645c184d51e0f9b34e1d7cf559"

S = "${WORKDIR}/git"

inherit go


do_compile(){
    go build statik.go
}

do_install(){
    install -d "${D}/${bindir}"
    install -m 0755 "${S}/statik" "${D}/${bindir}"
}

```

which compiles fine but I saw that your other class puts the go files somehow here:
/usr/lib/arm-poky-linux-gnueabi/go/src/

which the last code does not.

How should I do it best?
Just patch away the directory "example" in this case, but in my other funny this probably will not work.

there are also subdirectories with go files but those are probably necessary, and also I have to do a more complicated recipe due to some circle dependencies:

some stuff in https://github.com/Sirupsen/logrus depends on http://gopkg.in/gemnasium/logrus-airbrake-hook.v2 and the other way round.

Is there some standard way you can recommend when I just want to install some files, but keep them installed in the way you do so the referenced packages can be found.

Thanks,

Christian

**Comment by cyborg-x1** [comment]
Ahh found another recipe, that fixed my problems:

```
GO_INSTALL = "\
    ${GO_IMPORT} \
    ${GO_IMPORT}/hooks/... \
    "
```

**Comment by royemmerich** [comment]
I'm also trying to compile influxdb under yocto 2.1.2. I'd really appreciate it if you could share your work @cyborg-x1
